"""empty message

Revision ID: 0c764c2ddd91
Revises: b5fd58101a34
Create Date: 2022-05-23 11:34:08.247073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c764c2ddd91'
down_revision = 'b5fd58101a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orcamentos', 'orcstatus',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orcamentos', 'orcstatus',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
