"""empty message

Revision ID: 116653eee6d4
Revises: f7fe02956819
Create Date: 2022-06-03 10:10:27.278061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116653eee6d4'
down_revision = 'f7fe02956819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamados', sa.Column('chmStatus', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'chmStatus')
    # ### end Alembic commands ###
