"""empty message

Revision ID: 3d0aa3d62e1b
Revises: 3cd5ba8e75d9
Create Date: 2022-05-23 11:01:48.509985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0aa3d62e1b'
down_revision = '3cd5ba8e75d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teste', sa.Text(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('user', 'teste')
    # ### end Alembic commands ###
