"""empty message

Revision ID: 80a5ec8ab2b8
Revises: 3d0aa3d62e1b
Create Date: 2022-05-23 11:03:31.087791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a5ec8ab2b8'
down_revision = '3d0aa3d62e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teste', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
