"""empty message

Revision ID: aa43e1b30c6a
Revises: 116653eee6d4
Create Date: 2022-06-07 11:39:48.197130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa43e1b30c6a'
down_revision = '116653eee6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamados', sa.Column('textteste', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'textteste')
    # ### end Alembic commands ###
